### ISSUE TITLE
`cycles/008` non-determinate behavior in lightningcss

### ISSUE THREAD

**Issue by romainmenke** [romainmenke/css-import-tests#4]
This sometimes passes in lightningcss.
Smells like a race condition.

**Comment by romainmenke** [comment]
New location : https://github.com/romainmenke/css-import-tests/tree/main/tests/002-sub-features/003-at-layer/cycles/001

```
npm run serve 002-sub-features/003-at-layer/cycles/001
```

**Comment by romainmenke** [comment]
@devongovett steps to reproduce :

- clone this repo
- `npm ci`
- `npm run serve 002-sub-features/003-at-layer/cycles/001`
- visit `http://localhost:8080/lightningcss.html`
- refresh the page multiple times


When green the output is :

```css
@layer {
  .box {
    background-color: red;
  }
}

@layer {
  .box {
    background-color: green;
  }
}

@layer {
  
}
```

When red there is no output at all.  
Instead we get an error : `Unsupported layer combination in @import`

----

Because it sometimes fails and sometimes passes this seems to be a race condition?
Might be important to look into :)
